"""Senior developer interview — generated by conversation-tts skill."""
from __future__ import annotations
from pathlib import Path
import numpy as np
import soundfile as sf
from supertonic import TTS

OUTPUT = Path(__file__).with_suffix(".wav")
SAMPLE_RATE = 44100
PAUSE_MS = 350

SPEAKER_A = "interviewer"
SPEAKER_B = "candidate"
VOICE_A = "M1"
VOICE_B = "F1"

DIALOGUE: list[tuple[str, str]] = [
    ("interviewer", "Thanks for joining today. To kick things off, can you give me a quick summary of your background as a senior engineer?"),
    ("candidate",   "Of course. I have about ten years of experience, mostly in distributed systems. The last three years I have been the tech lead for a checkout platform that handles around two thousand transactions per second."),
    ("interviewer", "That is a meaningful scale. Walk me through one architectural decision you are particularly proud of."),
    ("candidate",   "We split the checkout flow into a synchronous price-and-reserve service and an asynchronous fulfillment pipeline. It cut p99 latency in half and let us roll out features in fulfillment without touching the hot path."),
    ("interviewer", "Where did the complexity move when you made that split?"),
    ("candidate",   "Mostly into eventual consistency. We had to add an idempotency key on every event, build a reconciliation job, and teach the support team how to read the new audit trail. The latency win was worth it, but the operational cost was real."),
    ("interviewer", "How do you decide when a refactor is worth shipping versus when to leave the code alone?"),
    ("candidate",   "I weigh three things. How often the code is touched, the blast radius if it breaks, and whether new requirements are bending it into an awkward shape. If two of those are high, I refactor. If only one is, I usually leave it."),
    ("interviewer", "Tell me about a time you disagreed with a teammate on a technical direction. How did you resolve it?"),
    ("candidate",   "A colleague wanted to introduce GraphQL for our internal admin tools. I thought REST was enough. Instead of arguing, we ran a two-week spike on one screen each. The data convinced him REST was simpler for our team size, and he ended up championing the decision."),
    ("interviewer", "Last question. What do you look for in your next role?"),
    ("candidate",   "A team that takes reliability seriously, room to mentor junior engineers, and a product where the technical problems actually matter to the business. If those three line up, I am usually happy."),
    ("interviewer", "Great answers all around. We will follow up with next steps by the end of the week. Thanks again."),
    ("candidate",   "Thank you. I really enjoyed the conversation."),
]


def main() -> None:
    print("[init] Loading Supertonic...", flush=True)
    tts = TTS(auto_download=True)
    styles = {
        SPEAKER_A: tts.get_voice_style(voice_name=VOICE_A),
        SPEAKER_B: tts.get_voice_style(voice_name=VOICE_B),
    }
    silence = np.zeros((1, int(SAMPLE_RATE * PAUSE_MS / 1000)), dtype=np.float32)
    chunks: list[np.ndarray] = []
    for i, (speaker, line) in enumerate(DIALOGUE, 1):
        preview = line[:60] + ("..." if len(line) > 60 else "")
        print(f"[{i:02d}/{len(DIALOGUE)}] {speaker}: {preview}", flush=True)
        wav, _ = tts.synthesize(
            text=line, lang="en",
            voice_style=styles[speaker],
            total_steps=8, speed=1.05,
        )
        if wav.ndim == 1:
            wav = wav.reshape(1, -1)
        chunks.append(wav.astype(np.float32))
        chunks.append(silence)
    full = np.concatenate(chunks, axis=1)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    sf.write(str(OUTPUT), full.squeeze(), SAMPLE_RATE, subtype="PCM_16")
    print(f"[done] {full.shape[1] / SAMPLE_RATE:.1f}s -> {OUTPUT}")


if __name__ == "__main__":
    main()
